name: hoytdotcom
favicon: null
layout_spectrum: 0.09935
typography_spectrum: 0.49675
title: hoytdotcom
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262331'
    - '#aeaba2'
    - '#475369'
    - '#fedba6'
    - '#b77235'
  brandStrength: 0.8683366789482534
  lightness: 0.25986675661988556
  saturation: 0.46381994360126555
  rhythmicContrast: 0.49642666801810265
purpose: []
